# Generated by Django 4.2 on 2023-04-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0009_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='posts',
        ),
        migrations.AddField(
            model_name='favorites',
            name='posts',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment'),
            preserve_default=False,
        ),
    ]
